# 苍穹外卖-用户端-C 端-用户接口

### POST 登录

POST /user/user/login HTTP/1.1
Host: {{host}}
token: {{jwt}}
Content-Type: application/json

{
"code": "string"
}

### POST 退出

POST /user/user/logout HTTP/1.1
Host: {{host}}
token: {{jwt}}
Content-Type: application/json
