sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: ${MYSQL_ROOT_PASSWORD}
  alioss:
    endpoint: oss-cn-beijing.aliyuncs.com
    access-key-id: ${OSS_ACCESS_KEY_ID}
    access-key-secret: ${OSS_ACCESS_KEY_SECRET}
    bucket-name: tlias-jacky
  redis:
    host: localhost
    port: 6379
    password:
    database: 10
  wechat:
    appid: ${WECHAT_APP_ID}
    secret: ${WECHAT_APP_PASSWORD}
    mchid : 1561414331
    mchSerialNo: 4B3B3DC35414AD50B1B755BAF8DE9CC7CF407606
    privateKeyFilePath: "/path/to/apiclient_key.pem"
    apiV3Key: CZBK51236435wxpay435434323FFDuv3
    weChatPayCertFilePath: "path/to/wechatpay_166D96F876F45C7D07CE98952A96EC980368ACFC.pem"
    notifyUrl: http://3d21ff43.r12.cpolar.top/notify/paySuccess
    refundNotifyUrl: http://3d21ff43.r12.cpolar.top/notify/refundSuccess
